services:
  web-el-imperio-del-dinero-frontend:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./Web-El-Imperio-del-Dinero:/app
    ports:
      - "4200:4200"
    environment:
      BROWSER: "none"
      SHELL: "/bin/bash"
      NODE_ENV: "local"