services:
  backend:
    build:
      context: ./BackEnd
      target: dev
    environment:
      PORT: 3000
      DB_FILENAME: /app/data/imperio_del_dinero.sqlite3
    ports:
      - "3000:3000"
    volumes:
      - ./BackEnd:/app
      - /app/node_modules
      - sqlite_data:/app/data
    restart: unless-stopped

  frontend:
    build:
      context: ./FrontEnd
      target: dev
    ports:
      - "4200:4200"
    volumes:
      - ./FrontEnd:/app
      - /app/node_modules
      - /app/.angular
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  sqlite_data:
